[project]
name = "ifra"
version = "1.0.0"
description = "Indonesia Flood Risk Analytics"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []
